name: form_concierge_flutter
description: A new Flutter project with Serverpod.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '^3.8.0'
  flutter: '^3.32.0'

dependencies:
  cupertino_icons: ^1.0.5
  flutter:
    sdk: flutter
  flutter_rearch: ^1.7.2
  form_concierge_client:
    path: ../form_concierge_client
  go_router: ^17.0.1
  rearch: ^1.16.1
  serverpod_auth_core_flutter: 3.2.3
  serverpod_flutter: 3.2.3
  uuid: ^4.5.1

dev_dependencies:
  flutter_lints: '>=3.0.0 <7.0.0'
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/config.json
